install.packages('rjson')
source("https://bioconductor.org/biocLite.R")
biocLite("shinyjs")
biocLite("shinyjs")
biocLite("shinythemes")
biocLite("lgatto/MSnbase")
biocLite("lme4")
devtools::install_github("statOmics/MSqRobData")
